version: "3.7"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mumsched
      MYSQL_DATABASE: mumsched
      MYSQL_USER: mumsched
      MYSQL_PASSWORD: mumsched

    volumes:
      - dbstore:/var/lib/mysql
    ports:
      - "3306:3306"


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"
    depends_on:
      - db


networks:
  backend:

volumes:
  dbstore:o